### ISSUE TITLE
cannot load postTransformation weight

### ISSUE THREAD

**Issue by wit543** [FreddeFrallan/Multilingual-CLIP#35]
After training, I attempt to convert TensorFlow weights (.index and .data-00000-of-00001) to a format that [pt_multilingual_clip.py](https://github.com/FreddeFrallan/Multilingual-CLIP/blob/main/multilingual_clip/pt_multilingual_clip.py) can use. However, the weights for the linear layer do not load properly.

error
```
Traceback (most recent call last):
  File "/multilingual_clip/TeacherLearning/ConvertTrainingModelToPT.py", line 39, in <module>
    splitAndStoreTFModelToDisk(transformerBase, weightsPath, visualDimensionSpace, modelSaveBase)
  File "/multilingual_clip/TeacherLearning/ConvertTrainingModelToPT.py", line 26, in splitAndStoreTFModelToDisk
    print("Saving Linear Weights into pickle file.", linearWeights.shape)
AttributeError: 'list' object has no attribute 'shape'
```
[weight not found](https://github.com/FreddeFrallan/Multilingual-CLIP/blob/93d894ed316b62cf882c649710252ed2d86f39c9/multilingual_clip/TeacherLearning/ConvertTrainingModelToPT.py#L26)

How to load properly?

**Comment by Lixinghan-cyber820** [comment]
that is because this post Transformation layer is lazy initialization,so you have to add an extra forward or build model like 
dummy_input = tf.random.uniform((1, 768))  
  _ = model.postTransformation(dummy_input)   
    then you can get the weight properly,and btw that one is just a list so you can use 
 print("Weights shape:", [w.shape for w in weights])
    print("Weights:", weights)
to print it but I dont think weights.shape works
